FROM continuumio/miniconda3:4.9.2
SHELL ["/bin/bash", "-c"]

RUN apt-get update --allow-releaseinfo-change && apt-get -y install gcc g++ make curl git
RUN conda install -c pytorch pytorch=1.9.0 torchserve=0.3.1 cpuonly
RUN conda install -c conda-forge openjdk=11 rdkit=2022.09.1
RUN pip install setuptools tqdm OpenNMT-py==1.2.0 dgl==0.4.3 networkx==2.5 pebble gdown
RUN pip install dgl==0.9.1
RUN pip install dgllife==0.2.6
RUN pip install epam.indigo

ENV CUDA_CODE cpu
ENV GPU_FLAG 0
ENV TORCH_VER 1.9.0
ENV DGLBACKEND pytorch

RUN pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-${TORCH_VER}+${CUDA_CODE}.html
RUN pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-${TORCH_VER}+${CUDA_CODE}.html
RUN pip install torch-cluster==1.5.9 -f https://data.pyg.org/whl/torch-${TORCH_VER}+${CUDA_CODE}.html
RUN pip install torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-${TORCH_VER}+${CUDA_CODE}.html
RUN pip install torch-geometric
RUN pip install torch-model-archiver

WORKDIR /app
COPY . /app/openretro
WORKDIR /app/openretro

# GLN installation -- CPU only
RUN cd ./models/gln_model && pip install -e .

# RDChiral installation
# Deprecated: RUN pip install -e "git://github.com/connorcoley/rdchiral.git#egg=rdchiral"
RUN pip install rdchiral

EXPOSE 8080 8081 8082

# Mask out GPUs temporarily, just in case
ENV CUDA_VISIBLE_DEVICES 10
