python preprocess.py \
  --model_name="retroxpert" \
  --stage=1 \
  --data_name="retroxpert_uspto_full" \
  --log_file="retroxpert_uspto_full_preprocess_s1" \
  --train_file="./data/retroxpert_uspto_full/raw/train.csv" \
  --val_file="./data/retroxpert_uspto_full/raw/valid.csv" \
  --test_file="./data/retroxpert_uspto_full/raw/test.csv" \
  --processed_data_path="./data/retroxpert_uspto_full/processed/" \
  --min_freq=10 \
  --num_cores=40