python test.py \
  --model_name="transformer" \
  --data_name="transformer-karpov" \
  --log_file="transformer_test" \
  --processed_data_path="./data/transformer-karpov/processed/" \
  --model_path="./checkpoints/transformer-karpov/model_step_500000.pt" \
  -batch_size 64 \
  -replace_unk \
  -max_length 200 \
  -beam_size 5 \
  -n_best 1 \
  -gpu 0
